alan_task:
    resource: "@AlanTaskBundle/Resources/config/routing.xml"
    prefix:   /

alan_blog:
    resource: "@AlanBlogBundle/Resources/config/routing.xml"
    prefix:   /

alan_test:
    resource: "@AlanTestBundle/Resources/config/routing.xml"
    prefix:   /

